name: Publish Package to NPM
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: cd projects/ny-component && npm run patch
            - run: rm yarn.lock
            - run: yarn install
            - run: yarn build:lib
            - run: npm publish ./dist/ng-components
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
